baseURL: 'https://ghector6.github.io/MakingDevs-Journey-Blog-/'
languageCode: en-us
title: MakingDevs Journey
theme: PaperMod
publishdir: docs
canonifyURLs: true
relativeURLs: true

params:
    homeInfoParams:
        Title: My journey
        Content: This is my personal blog to keep track of the subjects I'm going to be learning through my Making Devs journey...

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/ghector6"
        - name: "Twitter"
          url: "https://twitter.com/GHector6"
