baseURL: 'https://ghector6.github.io/MakingDevs-Journey-Blog-/'
languageCode: en-us
title: MakingDevs Journey
theme: PaperMod
publishdir: docs
canonifyURLs: true
relativeURLs: true

menu:
    main:
        - identifier: categories
          name: Categories
          url: categories/
          weight: 10 
        - identifier: tags
          name: Tags
          url: tags/
          weight: 20 
        - identifier: archives
          name: Archives
          url: archives/
          weight: 30 


disqusShortname: makingdevs-journey-blog

params:
    comments: true    
    profileMode: 
        enabled: true # needs to be explicitly set
        title: Hector´s Journey
        subtitle: "Welcome to my blog, learn with me"
        imageUrl: "img/Hector.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: Hector Garcia R,
        buttons:
          - name: Posts
            url: posts
          - name: Tags
            url: tags

    cover:
        linkFullImages: true

    ShowBreadCrumbs: true
    ShowReadingTime: true

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/ghector6"
        - name: "Twitter"
          url: "https://twitter.com/GHector6"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/ghector6/"

    assets: 
        disableHLJS: true 
        favicon: "img/favicon.ico" 
 #     favicon16x16: "<link / abs url>" 
 #     favicon32x32: "<link / abs url>" 
 #     apple_touch_icon: "<link / abs url>" 
 #     safari_pinned_tab: "<link / abs url>"


